permalink: /:categories/:title
markdown: redcarpet
exclude: .gitignore, Gemfile, Gemfile.lock, Procfile, Rakefile, readme.md

asset_pipeline:
  bundle: true            # Default = true
  compress: true          # Default = true
  output_path: assets     # Default = assets
  display_path: assets    # Default = nil
  gzip: true              # Default = false