source 'http://rubygems.org'
gem 'rake'
gem 'jekyll'
gem 'sass'
gem 'jammit'
gem 'coffee-script'
gem 'yui-compressor'
gem 'jekyll-asset-pipeline'
gem 'closure-compiler'
gem 'ruby-oembed'
gem 'redcarpet'
gem 'directory_watcher', '1.4.1'
